version: "3.9"

services:
  app_db:
    image: mysql:5.7
    volumes:
      - ./sqldb:/var/lib/mysql
    hostname: sqldb
    ports:
      # THIS PORT IS ONLY USED IN DEVELOPMENT!!
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: nestdb
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpw